version: "3.9"

networks:
  laravel:

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    image: nginx:stable
    ports:
      - 8000:80
    volumes:
    - ./:/var/www/html
    links:
      - fpm
    networks:
      - laravel

  fpm:
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
    volumes:
    - ./:/var/www/html
    links:
      - db
    networks:
      - laravel

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=passer
      - MYSQL_DATABASE=docker
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - db
    environment:
#      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=passer
      - UPLOAD_LIMIT=20M
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    command: ["composer", "install"]
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    links:
      - fpm
    restart: on-failure
    networks:
      - laravel
